### ISSUE TITLE
Weird behavior with same rule

### ISSUE THREAD

**Issue by Jannick94** [JannickMoodles/JValidate#4]
Issue came with commit f1385ee

When both inputs with same rule are empty, the validator sees them as valid. However this feels weird and not correct. Maybe make same rule required by default?

**Comment by StefanoGroenland** [comment]
![bugs](https://cloud.githubusercontent.com/assets/6575921/12891448/52e3c584-ce88-11e5-9979-bf67fb84d51c.png)

**Comment by mace015** [comment]
Ik vind eigelijk niet dat de velden bij de same methode automatisch required moeten zijn, wij bieden die same methode los en als gebruikers daarbij ook willen dat het veld vereist is dan moet dat mogelijk zijn, maar niet verplicht.
